version: '3'
services:
  bot-librarian:
    build: .
    container_name: bot-librarian
    image: bot-librarian
    command: node ./bin/bot-librarian.js
    ports:
      - "${BOT_EXTERNAL_PORT-:5000}:${BOT_INTERNAL_PORT:-5000}"
    environment:
      - PORT=${PORT:-5000}
